spring:
  datasource:
    username: root
    password: lb19182030
    url: jdbc:mysql://101.132.174.210:3306/gulimall_pms?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product
  thymeleaf:
    cache: false
  redis:
    host: 101.132.174.210
    port: 6379

#    suffix: .html
#    prefix: classpath:/templates
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
# MapperScan
# sql映射文件位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0 #逻辑已删除
      logic-not-delete-value: 1 #逻辑未删除
server:
  port: 10000
  #将com.atguigu.gulimall下面的日志改为debug 模式
logging:
  level:
    com.atguigu.gulimall: debug
##  HikariPool 较佳配置
#hikari:
#  connection-timeout: 60000
#  validation-timeout: 3000
#    idle-timeout: 60000
#    login-timeout: 5
#    max-lifetime: 60000
#    maximum-pool-size: 10
#    minimum-idle: 10
#    read-only: false
# 设置feign 的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000


