spring:
  datasource:
    username: root
    password: lb19182030
    url: jdbc:mysql://101.132.174.210:3306/gulimall_wms?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-ware
# MapperScan
# sql映射文件位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 11000


logging:
  level:
    com.atguigu: debug
# 设置feign 的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
